CREATE TYPE category_selection AS ENUM ('fiction', 'nonfiction', 'drama', 'poetry' );

CREATE TABLE Users (
    id INT NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    email VARCHAR UNIQUE NOT NULL,
    password VARCHAR(255) NOT NULL,
    firstname VARCHAR(255) NOT NULL,
    lastname VARCHAR(255) NOT NULL,
    address VARCHAR(255) NOT NULL,
    balance FLOAT NOT NULL,
    isSeller BOOLEAN DEFAULT FALSE
);

CREATE TABLE Products (
    id INT NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(255) UNIQUE NOT NULL,
    description VARCHAR(255) NOT NULL,
    price DECIMAL(12,2) NOT NULL,
    available BOOLEAN DEFAULT TRUE,
    category category_selection NOT NULL,
    createdAt timestamp without time zone NOT NULL DEFAULT (current_timestamp AT TIME ZONE 'UTC'),
    imageSrc VARCHAR(255) NOT NULL
);

--id for testing populating sample database for time being
CREATE TABLE Inventories (
    id INT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    sellerId INT NOT NULL REFERENCES Users(id),
    productId INT NOT NULL REFERENCES Products(id),
    quantity INT NOT NULL CHECK (quantity >= 0),
    PRIMARY KEY(id, sellerId, productId)
);

CREATE TABLE Orders (
    id INT NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    isFulfilled BOOLEAN DEFAULT FALSE,
    createdAt timestamp without time zone NOT NULL DEFAULT (current_timestamp AT TIME ZONE 'UTC')
);

CREATE TABLE CartItems (
    id INT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    ownerId INT NOT NULL REFERENCES Users(id),
    productId INT NOT NULL REFERENCES Products(id),
    orderId INT NOT NULL REFERENCES Orders,
    sellerId INT NOT NULL REFERENCES Users(id),
    quantity INT NOT NULL,
    isOrdered BOOLEAN DEFAULT FALSE,
    isFulfilled BOOLEAN DEFAULT FALSE,
    PRIMARY KEY(ownerId, productId, sellerId)
);

CREATE TABLE ProductReviews (
    id INT NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    createdAt timestamp without time zone NOT NULL DEFAULT (current_timestamp AT TIME ZONE 'UTC'),
    rating INT NOT NULL CHECK (rating >=1 AND rating <=5),
    description VARCHAR(255),
    productId INT NOT NULL REFERENCES Products(id),
    writerId INT NOT NULL
);

CREATE TABLE SellerReviews (
    id INT NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    createdAt timestamp without time zone NOT NULL DEFAULT (current_timestamp AT TIME ZONE 'UTC'),
    rating INT NOT NULL CHECK (rating >=1 AND rating <=5),
    description VARCHAR(255),
    sellerId INT NOT NULL REFERENCES Users(id),
    writerId INT NOT NULL REFERENCES Users(id)
);
